name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]  # yoki master bo‘lsa, shuni yozing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.dckr_pat_jGShHHtTFSEvg7hBJ6v5lPAmYxQ }}" | docker login -u "${{ secrets.nurullo1999 }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.nurullo1999 }}/flask-app .

    - name: Push to Docker Hub
      run: docker push ${{ secrets.nurullo1999 }}/flask-app
